export let feature_dict = {
    "teacher_total_full_time_equiv":"Full Time Teachers (Count)", 
      "school_admin_total_full_time_equiv":"Full Time Admin Staff (Count)",
      "teacher_total_base_salary":"Teacher Average Base Salary ($)",
      "teacher_1_5_years_full_time_equiv":"Teacher 1-5 Years Experience (Count)",
      "teacher_6_10_years_full_time_equiv":"Teacher 6-10 Years Experience (Count)",
      "teacher_11_20_years_full_time_equiv":"Teacher 11-20 Years Experience (Count)",
      "teacher_20_years_full_time_equiv":"Teacher 20 Years+ Experience (Count)",
      "teacher_1_5_years_base_salary":"Teacher Average Salary 1-5 Years Experience ($)",
      "teacher_6_10_years_base_salary":"Teacher Average Salary 6-10 Years Experience ($)",
      "teacher_11_20_years_base_salary":"Teacher Average Salary 11-20 Years Experience ($)",
      "teacher_male_full_time_equiv":"Full Time Male Teachers (Count)",
      "teacher_female_full_time_equiv":"Full Time Female Teachers (Count)",
      "teacher_no_degree_full_time_equiv":"Teachers with no Degree (Count)",
      "teacher_ba_degree_full_time_equiv":"Teachers with Bachelors Degree (Count)",
      "teacher_ms_degree_full_time_equiv":"Teachers with Masters Degree (Count)",
      "teacher_student_ratio":"Teacher Student Ratio (%)",
      "all_students":"Number of Students",
      "white":"Number of White Students",
      "african_american":"Number of African Amercian Students",
      "hispanic":"Number of Hispanic Students",
      "at_risk":"Number of At Risk Students",
      "economic_disadvant":"Number of Economic Disadvantaged Students",
      "Grade_Leve_Elementary":0,
      "Grade_Leve_Elementary/Secondary":0,
      "Grade_Leve_High School":0,
      "Grade_Leve_Junior High":0,
      "Grade_Leve_Middle":0,
      "new_rate":"Student Performance (Meets Standards,%)",
      "teacher_experience":"Teacher Experience (Avg Years)",
      "principal_experience": "Principal Experience (Avg Years)",
      "assistant_principal_count": "Assistant Principal Count"
  }